#ifndef VIEWSTATES_H
#define VIEWSTATES_H

#include "CommonDefine.h"

BEGIN_NAMESPACE(App)

DECLARE_FUNC_STATE(SCREEN_A)
DECLARE_FUNC_STATE(SCREEN_B)
DECLARE_FUNC_STATE(SCREEN_C)

DECLARE_FUNC_STATE(POPUP_X)
DECLARE_FUNC_STATE(POPUP_Y)
DECLARE_FUNC_STATE(POPUP_Z)

DEFINE_EMPTY_FUNC_STATE(TOAST_SUCCESS)
DEFINE_EMPTY_FUNC_STATE(TOAST_FAIL)

DEFINE_EMPTY_FUNC_STATE(NOTIFY_INFO)
DEFINE_EMPTY_FUNC_STATE(NOTIFY_WARN)
DEFINE_EMPTY_FUNC_STATE(NOTIFY_ERROR)

END_NAMESPACE

#endif // VIEWSTATES_H
