#include "ViewStates.h"
#include "Logger/LoggerDefines.h"

void SCREEN_A_ENTRY() { CPP_LOG_DEBUG("[ENTRY][SCREEN A]");}
void SCREEN_A_BACK() { CPP_LOG_DEBUG("[BACK][SCREEN A]");}
void SCREEN_A_EXIT() { CPP_LOG_DEBUG("[EXIT][SCREEN A]");}

void SCREEN_B_ENTRY() { CPP_LOG_DEBUG("[ENTRY][SCREEN B]");}
void SCREEN_B_BACK() { CPP_LOG_DEBUG("[BACK][SCREEN B]");}
void SCREEN_B_EXIT() { CPP_LOG_DEBUG("[EXIT][SCREEN B]");}

void SCREEN_C_ENTRY() { CPP_LOG_DEBUG("[ENTRY][SCREEN C]");}
void SCREEN_C_BACK() { CPP_LOG_DEBUG("[BACK][SCREEN C]");}
void SCREEN_C_EXIT() { CPP_LOG_DEBUG("[EXIT][SCREEN C]");}

void POPUP_X_ENTRY() { CPP_LOG_DEBUG("[ENTRY][POPUP X]");}
void POPUP_X_BACK() { CPP_LOG_DEBUG("[BACK][POPUP X]");}
void POPUP_X_EXIT() { CPP_LOG_DEBUG("[EXIT][POPUP X]");}

void POPUP_Y_ENTRY() { CPP_LOG_DEBUG("[ENTRY][POPUP Y]");}
void POPUP_Y_BACK() { CPP_LOG_DEBUG("[BACK][POPUP Y]");}
void POPUP_Y_EXIT() { CPP_LOG_DEBUG("[EXIT][POPUP Y]");}

void POPUP_Z_ENTRY() { CPP_LOG_DEBUG("[ENTRY][POPUP Z]");}
void POPUP_Z_BACK() { CPP_LOG_DEBUG("[BACK][POPUP Z]");}
void POPUP_Z_EXIT() { CPP_LOG_DEBUG("[EXIT][POPUP Z]");}

