#ifndef VIEWDATA_H
#define VIEWDATA_H

#include "Common.h"
#include "ViewStates.h"
#include "CViewEnums.h"
#include "ViewDefines.h"


// [screens]
static const S_VIEW_INFORMATION SCREEN_A_INFORMATION = {
    E_SCREEN_ID::E_SCREEN_A_ID,
    &SCREEN_A_ENTRY,
    &SCREEN_A_EXIT,
    E_DURATION::NONE,
    E_VIEW_TYPE::SCREEN_TYPE,
    SCREEN_A
};

static const S_VIEW_INFORMATION SCREEN_B_INFORMATION = {
    E_SCREEN_ID::E_SCREEN_B_ID,
    &SCREEN_B_ENTRY,
    &SCREEN_B_EXIT,
    E_DURATION::NONE,
    E_VIEW_TYPE::SCREEN_TYPE,
    SCREEN_B
};

static const S_VIEW_INFORMATION SCREEN_C_INFORMATION = {
    E_SCREEN_ID::E_SCREEN_C_ID,
    &SCREEN_C_ENTRY,
    &SCREEN_C_EXIT,
    E_DURATION::NONE,
    E_VIEW_TYPE::SCREEN_TYPE,
    SCREEN_C
};
// [popups]
static const S_VIEW_INFORMATION POPUP_X_INFORMATION = {
    E_POPUP_ID::E_POPUP_X_ID,
    &POPUP_X_ENTRY,
    &POPUP_X_EXIT,
    E_DURATION::IN_5_SECS,
    E_VIEW_TYPE::POPUP_TYPE,
    POPUP_X
};

static const S_VIEW_INFORMATION POPUP_Y_INFORMATION = {
    E_POPUP_ID::E_POPUP_Y_ID,
    &POPUP_Y_ENTRY,
    &POPUP_Y_EXIT,
    E_DURATION::NONE,
    E_VIEW_TYPE::POPUP_TYPE,
    POPUP_Y
};

static const S_VIEW_INFORMATION POPUP_Z_INFORMATION = {
    E_POPUP_ID::E_POPUP_Z_ID,
    &POPUP_Z_ENTRY,
    &POPUP_Z_EXIT,
    E_DURATION::NONE,
    E_VIEW_TYPE::POPUP_TYPE,
    POPUP_Z
};

static const S_VIEW_INFORMATION ALL_INFOR[6] = {
    SCREEN_A_INFORMATION,
    SCREEN_B_INFORMATION,
    SCREEN_C_INFORMATION,
    POPUP_X_INFORMATION,
    POPUP_Y_INFORMATION,
    POPUP_Z_INFORMATION
};

static const S_VIEW_EVENT  ALL_EVENTS[18] = {
    // [screen A]
    {E_SCREEN_ID::E_SCREEN_A_ID, CViewEnums::E_SCREEN_A_EVT_SHOW, &SCREEN_A_ENTRY, E_SCREEN_ID::E_SCREEN_A_ID},
    {E_SCREEN_ID::E_SCREEN_A_ID, CViewEnums::E_SCREEN_A_EVT_NAV_SCREEN_B, &SCREEN_B_ENTRY, E_SCREEN_ID::E_SCREEN_B_ID},
    {E_SCREEN_ID::E_SCREEN_A_ID, CViewEnums::E_SCREEN_A_EVT_NAV_SCREEN_C, &SCREEN_C_ENTRY, E_SCREEN_ID::E_SCREEN_C_ID},
    {E_SCREEN_ID::E_SCREEN_A_ID, CViewEnums::E_SCREEN_A_EVT_OPEN_POPUP_X, &POPUP_X_ENTRY, E_POPUP_ID::E_POPUP_X_ID},
    // [screen B]
    {E_SCREEN_ID::E_SCREEN_B_ID, CViewEnums::E_SCREEN_B_EVT_SHOW, &SCREEN_B_ENTRY, E_SCREEN_ID::E_SCREEN_B_ID},
    {E_SCREEN_ID::E_SCREEN_B_ID, CViewEnums::E_SCREEN_B_EVT_NAV_SCREEN_A, &SCREEN_A_ENTRY, E_SCREEN_ID::E_SCREEN_A_ID},
    {E_SCREEN_ID::E_SCREEN_B_ID, CViewEnums::E_SCREEN_B_EVT_NAV_SCREEN_C, &SCREEN_C_ENTRY, E_SCREEN_ID::E_SCREEN_C_ID},
    {E_SCREEN_ID::E_SCREEN_B_ID, CViewEnums::E_SCREEN_B_EVT_OPEN_POPUP_X, &POPUP_X_ENTRY, E_POPUP_ID::E_POPUP_X_ID},
    // [screen C]
    {E_SCREEN_ID::E_SCREEN_C_ID, CViewEnums::E_SCREEN_C_EVT_SHOW, &SCREEN_B_ENTRY, E_SCREEN_ID::E_SCREEN_C_ID},
    {E_SCREEN_ID::E_SCREEN_C_ID, CViewEnums::E_SCREEN_C_EVT_NAV_SCREEN_A, &SCREEN_A_ENTRY, E_SCREEN_ID::E_SCREEN_A_ID},
    {E_SCREEN_ID::E_SCREEN_C_ID, CViewEnums::E_SCREEN_C_EVT_NAV_SCREEN_B, &SCREEN_B_ENTRY, E_SCREEN_ID::E_SCREEN_B_ID},
    {E_SCREEN_ID::E_SCREEN_C_ID, CViewEnums::E_SCREEN_C_EVT_OPEN_POPUP_X, &POPUP_X_ENTRY, E_POPUP_ID::E_POPUP_X_ID},
    // [popup X]
    {E_POPUP_ID::E_POPUP_X_ID, CViewEnums::E_POPUP_X_EVT_SHOW, &POPUP_X_ENTRY, E_POPUP_ID::E_POPUP_X_ID},
    {E_POPUP_ID::E_POPUP_X_ID, CViewEnums::E_POPUP_X_EVT_NAV_SCREEN_A, &SCREEN_A_ENTRY, E_SCREEN_ID::E_SCREEN_A_ID},
    // [popup Y]
    {E_POPUP_ID::E_POPUP_Y_ID, CViewEnums::E_POPUP_Y_EVT_SHOW, &POPUP_Y_ENTRY, E_POPUP_ID::E_POPUP_Y_ID},
    {E_POPUP_ID::E_POPUP_Y_ID, CViewEnums::E_POPUP_Y_EVT_NAV_SCREEN_B, &SCREEN_A_ENTRY, E_SCREEN_ID::E_SCREEN_B_ID},
    // [popup Z]
    {E_POPUP_ID::E_POPUP_Z_ID, CViewEnums::E_POPUP_Z_EVT_SHOW, &POPUP_Z_ENTRY, E_POPUP_ID::E_POPUP_Z_ID},
    {E_POPUP_ID::E_POPUP_Z_ID, CViewEnums::E_POPUP_Z_EVT_NAV_SCREEN_C, &SCREEN_A_ENTRY, E_SCREEN_ID::E_SCREEN_C_ID},
};

#endif // VIEWDATA_H
