#ifndef VIEWSTATES_H
#define VIEWSTATES_H

#define DECLARE_FUNC_STATE(NAME) \
void NAME##_ENTRY(); \
void NAME##_BACK(); \
void NAME##_EXIT();

#define DEFINE_FUNC_STATE(NAME) \
void NAME##_ENTRY(){} \
void NAME##_BACK(){} \
void NAME##_EXIT(){}

DECLARE_FUNC_STATE(SCREEN_A)
DECLARE_FUNC_STATE(SCREEN_B)
DECLARE_FUNC_STATE(SCREEN_C)

DECLARE_FUNC_STATE(POPUP_X)
DECLARE_FUNC_STATE(POPUP_Y)
DECLARE_FUNC_STATE(POPUP_Z)

DECLARE_FUNC_STATE(TOAST_SUCCESS)
DECLARE_FUNC_STATE(TOAST_FAIL)

DECLARE_FUNC_STATE(NOTIFY_INFO)
DECLARE_FUNC_STATE(NOTIFY_WARN)
DECLARE_FUNC_STATE(NOTIFY_ERROR)


#endif // VIEWSTATES_H
